config/routes.rb
Halofest::Application.routes.draw do

  devise_for :users

  resources :keepers

  resources :picks

  resources :draft_rounds

  resources :drafts

  resources :rosters

  resources :players do
    resources :player_stats, except:[:show]
  end

  resources :sessions, only: [:new, :create, :destroy]

  resources :users

  root "home#index"

  get "home/index"

end

app/models/roster.rb
class Roster < ActiveRecord::Base
  belongs_to :user
  belongs_to :draft
  has_and_belongs_to_many :players

  validates :user_id, :draft_id, presence: true
end

app/controllers/rosters_controller.rb
class RostersController < LoggedInController
  before_action :set_roster, only: [:show, :edit, :update, :destroy]

  # GET /rosters
  # GET /rosters.json
  def index
    @rosters = Roster.all
  end

  # GET /rosters/1
  # GET /rosters/1.json
  def show
  end

  # GET /rosters/new
  def new
    @roster = Roster.new
  end

  # GET /rosters/1/edit
  def edit
  end

  # POST /rosters
  # POST /rosters.json
  def create
    @roster = Roster.new(roster_params)

    respond_to do |format|
      if @roster.save
        format.html { redirect_to @roster, notice: 'Roster was successfully created.' }
        format.json { render action: 'show', status: :created, location: @roster }
      else
        format.html { render action: 'new' }
        format.json { render json: @roster.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rosters/1
  # PATCH/PUT /rosters/1.json
  def update
    respond_to do |format|
      if @roster.update(roster_params)
        format.html { redirect_to @roster, notice: 'Roster was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @roster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rosters/1
  # DELETE /rosters/1.json
  def destroy
    @roster.destroy
    respond_to do |format|
      format.html { redirect_to rosters_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_roster
      @roster = Roster.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def roster_params
      params.require(:roster).permit(:user_id, :draft_id)
    end
end

app/views/rosters/_form.html.haml
.row
  .col-sm-6.col-sm-offset-2
    = form_for @roster do |f|
      - if @roster.errors.any?
        #error_explanation
          %h2= "#{pluralize(@roster.errors.count, "error")} prohibited this roster from being saved:"
          %ul
            - @roster.errors.full_messages.each do |msg|
              %li= msg

      .field
        = f.label :user_id, class: "col-sm-2 control-label"
        .col-sm-10
          = f.collection_select :user_id, User.all, :id, :name, {}, {class: 'form-control'}

      .field
        = f.label :draft_id, class: "col-sm-2 control-label"
        .col-sm-10
          = f.collection_select :draft_id, Draft.all, :id, :year, {}, {class: 'form-control'}

      .actions
        = f.submit 'Save', class: 'btn btn-primary'

app/views/rosters/edit.html.haml
%h1 Editing roster

= render 'form'

= link_to 'Show', @roster
\|
= link_to 'Back', rosters_path

app/views/rosters/index.html.haml
%h1 Rosters

%table.table.table-striped
  %tr
    %th User
    %th Draft
    %th
    %th
    %th

  - @rosters.each do |roster|
    %tr
      %td= link_to roster.user.name, roster_path(roster.user)
      %td= roster.draft.year
      %td
        = link_to 'Show', roster, class: 'btn btn-xs btn-info'
        = link_to 'Edit', edit_roster_path(roster), class: 'btn btn-xs btn-warning'
        = link_to 'Destroy', roster, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-xs btn-danger'

%br

= link_to 'New Roster', new_roster_path

app/views/rosters/new.html.haml
%h1 New roster

= render 'form'

= link_to 'Back', rosters_path

app/views/rosters/show.html.haml
%p
  %b User:
  = @roster.user.name
%p
  %b Draft:
  = @roster.draft.year

%table.table.table-striped.table-bordered.table-condensed
  %thead
    %th Name
    %th Year
    %th FGM
    %th FGA
    %th FTM
    %th FTA
    %th REB
    %th AST
    %th STL
    %th BLK
    %th TO
    %th PTS
    %th Fantasy Pts (total)
    %th Fantasy Pts (average)
    %th Keeper?
    %th Keeper Cost
  %tbody
    - @roster.players.each do |player|
      %tr
        %td= link_to player.full_name, player_path(player)
        - stats = player.player_stats.where(year: @roster.draft.year).first
        - unless stats.blank?
          %td= stats.year
          %td= stats.fgm
          %td= stats.fga
          %td= stats.ftm
          %td= stats.fta
          %td= stats.reb
          %td= stats.ast
          %td= stats.stl
          %td= stats.blk
          %td= stats.to
          %td= stats.pts
          %td= stats.fpts_total
          %td= stats.fpts_avg
          %td
          %td

= link_to 'Edit', edit_roster_path(@roster), class: 'btn btn-xs btn-warning'
\|
= link_to 'Back', rosters_path, class: 'btn btn-xs btn-info'