config/routes.rb
Halofest::Application.routes.draw do

  devise_for :users

  resources :keepers

  resources :picks

  resources :draft_rounds

  resources :drafts

  resources :rosters

  resources :players do
    resources :player_stats, except:[:show]
  end

  resources :sessions, only: [:new, :create, :destroy]

  resources :users

  root "home#index"

  get "home/index"

end

app/models/player_stats.rb
class PlayerStats < ActiveRecord::Base
  belongs_to :player
end

app/controllers/player_stats_controller.rb
class PlayerStatsController < LoggedInController
  before_action :load_player
  before_action :admin_user, only: [:edit, :update, :destroy]

  # GET /player_stats/new
  def new
    @player_stats = @player.player_stats.new
  end

  # GET /player_stats/1/edit
  def edit
  end

  # POST /player_stats
  def create
    @player_stats = @player.player_stats.new(player_stat_params)

    if @player_stats.save
      redirect_to player_path(@player), notice: 'Player stats were successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /player_stats/1
  def update
    if @player_stats.update(player_stat_params)
      redirect_to player_path(@player), notice: 'Player stats were successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /player_stats/1
  def destroy
    @player_stats.destroy
    redirect_to player_path(@player)
  end

  private

  def load_player
    @player = Player.find params[:player_id]
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

  def load_player_stat
    @player_stats = PlayerStats.find params[:id]
  end

  def player_stat_params
    params.require(:player_stats).permit(
      :year,
      :fgm, :fga, :ftm, :fta, :reb, :ast, :stl, :blk, :to, :pts,
      :fpts_total, :fpts_avg
    )
  end
end

app/views/player_stats/_form.html.haml
- if @player_stats.new_record?
  - url = player_player_stats_path(@player, @player_stats)
- else
  - url = player_player_stat_path(@player, @player_stats)

= form_for @player_stats, url: url do |f|

  - if @player_stats.errors.any?
    #error_explanation
      %h2= "#{pluralize(@player_stats.errors.count, "error")} prohibited this player_stat from being saved:"
      %ul
        - @player_stats.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :year
    = f.number_field :year
  .field
    = f.label :fgm
    = f.text_field :fgm, :autocomplete => :off
  .field
    = f.label :fga
    = f.text_field :fga, :autocomplete => :off
  .field
    = f.label :ftm
    = f.text_field :ftm, :autocomplete => :off
  .field
    = f.label :fta
    = f.text_field :fta, :autocomplete => :off
  .field
    = f.label :reb
    = f.text_field :reb, :autocomplete => :off
  .field
    = f.label :ast
    = f.text_field :ast, :autocomplete => :off
  .field
    = f.label :stl
    = f.text_field :stl, :autocomplete => :off
  .field
    = f.label :blk
    = f.text_field :blk, :autocomplete => :off
  .field
    = f.label :to
    = f.text_field :to, :autocomplete => :off
  .field
    = f.label :pts
    = f.text_field :pts, :autocomplete => :off
  .field
    = f.label :fpts_total
    = f.text_field :fpts_total, :autocomplete => :off
  .field
    = f.label :fpts_avg
    = f.text_field :fpts_avg, :autocomplete => :off
  .actions
    = f.submit 'Save', class: 'btn btn-primary'

app/views/player_stats/edit.html.haml
%h1
  Editing Stats for
  = @player.full_name

= render 'form'

= link_to 'Back', player_path(@player)

app/views/player_stats/index.html.haml
%h1 Listing player_stats

%table
  %tr
    %th Player
    %th Year
    %th Fpts total
    %th Fpts avg
    %th
    %th
    %th

  - @player_stats.each do |player_stat|
    %tr
      %td= player_stat.player_id
      %td= player_stat.year
      %td= player_stat.fpts_total
      %td= player_stat.fpts_avg
      %td= link_to 'Show', player_stat
      %td= link_to 'Edit', edit_player_stat_path(player_stat)
      %td= link_to 'Destroy', player_stat, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Player stat', new_player_stat_path

app/views/player_stats/new.html.haml
%h1
  New Stats for
  = @player_stats.player.full_name

= render 'form'

= link_to 'Back', player_path(@player)

app/views/player_stats/show.html.haml
%p
  %b Player:
  = @player_stat.player_id
%p
  %b Year:
  = @player_stat.year
%p
  %b Fpts total:
  = @player_stat.fpts_total
%p
  %b Fpts avg:
  = @player_stat.fpts_avg

= link_to 'Edit', edit_player_stat_path(@player_stat)
\|
= link_to 'Back', player_stats_path