config/routes.rb
Halofest::Application.routes.draw do

  devise_for :users

  resources :keepers

  resources :picks

  resources :draft_rounds

  resources :drafts

  resources :rosters

  resources :players do
    resources :player_stats, except:[:show]
  end

  resources :sessions, only: [:new, :create, :destroy]

  resources :users

  root "home#index"

  get "home/index"

end

app/models/player.rb
class Player < ActiveRecord::Base
  has_many :player_stats, class_name: 'PlayerStats', :dependent => :destroy
  has_and_belongs_to_many :rosters
  has_many :keepers

  validates :first_name, presence: true

  def full_name
    [first_name, last_name].reject(&:blank?).join(" ")
  end

  def as_json(options={})
        {
          fpts_total: player_stats.map { |ps| { ps.year => ps.fpts_total } }
        }
    end
end

app/controllers/players_controller.rb
class PlayersController < LoggedInController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.includes(:player_stats).all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render action: 'show', status: :created, location: @player }
      else
        format.html { render action: 'new' }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:first_name, :last_name)
    end
end

app/views/players/_form.html.haml
= form_for @player do |f|
  - if @player.errors.any?
    #error_explanation
      %h2= "#{pluralize(@player.errors.count, "error")} prohibited this player from being saved:"
      %ul
        - @player.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :first_name
    = f.text_field :first_name, :autocomplete => :off
  .field
    = f.label :last_name
    = f.text_field :last_name, :autocomplete => :off


  .actions
    = f.submit 'Save'

app/views/players/edit.html.haml
%h1 Editing player

= render 'form'

= link_to 'Show', @player
\|
= link_to 'Back', players_path

app/views/players/index.html.haml
%h1 Listing players

%table.table.table-striped
  %tr
    %th Name
    %th Year
    %th FGM
    %th FGA
    %th FTM
    %th FTA
    %th REB
    %th AST
    %th STL
    %th BLK
    %th TO
    %th PTS
    %th FPTS TOT
    %th FPTS AVG
    %th

  - @players.each do |player|
    %tr
      %td= link_to player.full_name, player_path(player)
      - stats = player.player_stats.sort { |player| player.year }.last
      %td= stats.try :year
      %td= stats.try :fgm
      %td= stats.try :fga
      %td= stats.try :ftm
      %td= stats.try :fta
      %td= stats.try :reb
      %td= stats.try :ast
      %td= stats.try :stl
      %td= stats.try :blk
      %td= stats.try :to
      %td= stats.try :pts
      %td= stats.try :fpts_total
      %td= stats.try :fpts_avg
      %td
        = link_to 'Show', player, class: 'btn btn-xs btn-info'
        = link_to 'Edit', edit_player_path(player), class: 'btn btn-xs btn-warning'
        = link_to 'Destroy', player, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-xs btn-danger'

%script{type:'application/javascript'}
window.data = #{@players.first.to_json.html_safe};

app/views/players/new.html.haml
%h1 New player

= render 'form'

= link_to 'Back', players_path

app/views/players/show.html.haml
%p
  %b Name
  = @player.full_name


= link_to "Edit", edit_player_path(@player), class: "btn btn-xs btn-warning"


- if @player.player_stats.any?
  %h3 Stats
  %table.table.table-bordered.table-striped
    %thead
      %tr
        %th Year
        %th FGM
        %th FGA
        %th FTM
        %th FTA
        %th REB
        %th AST
        %th STL
        %th BLK
        %th TO
        %th PTS
        %th Fantasy Pts (total)
        %th Fantasy Pts (average)
        %th
    %tbody
      - @player.player_stats.order("year DESC").each do |stats|
        %tr
          %td= stats.year
          %td= stats.fgm
          %td= stats.fga
          %td= stats.ftm
          %td= stats.fta
          %td= stats.reb
          %td= stats.ast
          %td= stats.stl
          %td= stats.blk
          %td= stats.to
          %td= stats.pts
          %td= stats.fpts_total
          %td= stats.fpts_avg
          %td
            = link_to "Edit", edit_player_player_stat_path(@player, stats), class: "btn btn-xs btn-warning"
            = link_to "Delete", player_player_stat_path(@player, stats), method: :delete,
                      class: "btn btn-xs btn-danger", data: { confirm: "Are you sure?" }

  = link_to "New Stats Year", new_player_player_stat_path(@player), class: "btn btn-sm btn-primary"

- else

  = link_to "New Stats Year", new_player_player_stat_path(@player), class: "btn btn-sm btn-primary"
%br
%br
= link_to "Back", players_path, class: 'btn btn-xs btn-info'