config/routes.rb
Halofest::Application.routes.draw do

  devise_for :users

  resources :keepers

  resources :picks

  resources :draft_rounds

  resources :drafts

  resources :rosters

  resources :players do
    resources :player_stats, except:[:show]
  end

  resources :sessions, only: [:new, :create, :destroy]

  resources :users

  root "home#index"

  get "home/index"

end

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-inverse{role:"navigation"}
  <!-- Brand and toggle get grouped for better mobile display -->
  .navbar-header
    %button.navbar-toggle{type:"button", data: { toggle:"collapse", target:"#bs-example-navbar-collapse-1"} }
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    = link_to "HaloFest", root_path, class: "navbar-brand"

  <!-- Collect the nav links, forms, and other content for toggling -->
  .collapse#bs-example-navbar-collapse-1.navbar-collapse

    - if user_signed_in?
      %ul.nav.navbar-nav
        %li
          = link_to "Home", root_path
        %li
          = link_to "Users", users_path
        %li
          = link_to "Players", players_path
        %li
          = link_to "Rosters", rosters_path
        %li
          = link_to "Drafts", drafts_path
        %li
          = link_to "Draft Rounds", draft_rounds_path
        %li
          = link_to "Picks", picks_path

      %ul.nav.navbar-nav.navbar-right
        %li.dropdown
          %a.dropdown-toggle{href: '#', data: {toggle: 'dropdown'} }
            = current_user.name
            %b.caret
          %ul.dropdown-menu
            %li
              = link_to "Log Out", destroy_user_session_path, method: 'delete'
    - else
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to "Log In", new_user_session_path

app/views/layouts/application.html.haml
!!!5
%html
  %head
    %title HaloFest
    %meta{name:"viewport", content:"width=device-width, initial-scale=1.0"}
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    %script{src:"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"}
    %script{src:"https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"}
    <![endif]-->
    = csrf_meta_tags
  %body
    .container
      = render 'layouts/navbar'

      - flash.each do |type, msg|
        .alert{ class: "alert-#{type.to_s == 'notice' ? 'success' : 'danger'}" }
          %button.close{ type: 'button',
                         data: { dismiss: 'alert'},
                         'aria-hidden' => 'true'}
            &times;

          = msg.gsub("\n", '<br>').html_safe

      = yield

  #load_javascripts
    = javascript_include_tag "application", "data-turbolinks-track" => true